// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.chaquo.python:gradle:16.1.0'
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
    }
    // Set a shorter build directory path to prevent Windows MAX_PATH character limit errors
    buildDir = "C:/tmp/sb/${project.name}"
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
